### PR TITLE
New input parameter to set the runner for the workflow

### LINKED ISSUE #8: Add a parameter to specify the runner
@leonheldattoradex 
This is related to [this topic](https://community.toradex.com/t/mouse-and-touch-screen-dont-work-with-cog-imx8-container/25291/13) on Toradex community.

With a new parameter to specify the runner, it would be possible using a self-hosted agent to overcome the limitations of the free github plan.

### PR DESCRIPTION
**Pull request by escherstair**
Implements what is discussed in #8 and [on Toradex community](https://community.toradex.com/t/mouse-and-touch-screen-dont-work-with-cog-imx8-container/25291/13)

Closes: torizon/torizon-deb-ci#8

### CODE REVIEW

**Comment by leograba** [comment]
Thanks @escherstair, we'll review and as soon as there's an update provide you some feedback here

**Comment by charles2910** [comment]
Hi, @escherstair.

Sorry for taking so long.

Changes look good! Are you using self-hosted runners? We don't have the need right now, but it's a nice change and I think it's merge material.

Can I just ask for you to add `Closes: torizon/torizon-deb-ci#8` to the long description so it automatically closes the issue and we have a paper trail on the git history itself?

After that I'll merge the PR!

**Comment by escherstair** [comment]
Hi @charles2910,

> Can I just ask for you to add `Closes: torizon/torizon-deb-ci#8` to the long description so it automatically closes the issue and we have a paper trail on the git history itself?

Not sure if I added it in the right place.
If not, can you exaplain me where I should add it?

**Comment by charles2910** [comment]
Hey @escherstair, just merged!

> Not sure if I added it in the right place.
> If not, can you exaplain me where I should add it?

I should have been more clear, sorry. I was talking about adding it to the commit's long description with `git commit --amend`. But since you've added to the PR description it's caught in the merge commit and has the same effect, so no problem here.

Thanks for the contribution!

**Pull request merged**
